version: '2'
services:
    db:
        image: mysql:5.7
        volumes:
            - ~/.short-service/data:/var/lib/mysql
        environment:
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=short
            - MYSQL_USER=short
    redis:
        image: redis
    api-server:
        image: busybox
        volumes:
            - ~/sites/short-url/server:/go
        command: /go/up-short-url
        ports:
            - "9654:9654"
        depends_on:
            - db
            - redis
        links:
            - db
            - redis