version: '2'
services:
    db:
        image: mysql
        volumes:
            - ~/sites/short-url/data:/var/lib/mysql
        environment:
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=short
            - MYSQL_USER=short
            - MYSQL_ROOT_PASSWORD=short
    api-server:
        image: alpine
        volumes:
            - ~/sites/short-url/server:/go
        command: /go/up-short-url
        ports:
            - "9999:9999"
        depends_on:
            - db
        links:
            - db